stages modified as generating sbom file and uploading to dependency server and checking vulnerabilities

diff --git a/test_deepseek/Jenkinsfile b/test_deepseek/Jenkinsfile
--- a/test_deepseek/Jenkinsfile
+++ b/test_deepseek/Jenkinsfile
@@ -1,110 +1,131 @@
 #!/usr/bin/env groovy
 
 pipeline {
-    agent any
+  agent any
 
-    environment {
-        DEP_TRACK_API_URL = 'http://localhost:8080/api'
-        DEP_TRACK_API_KEY = 'odt_LiwdxLe1XPY8608S0S6huqCQkDDlnz23'
-        SBOM_FILE_PATH = 'target/bom.xml'
+  environment {
+    DEP_TRACK_API_URL = 'http://localhost:8081/api'
+    DEP_TRACK_API_KEY = 'odt_IrMmeW3Hy3zDbxG1SxVD5S8MwqOUYNEk'
+    SBOM_FILE_PATH = 'target/bom.xml'
+  }
+
+  stages {
+    stage("Build") {
+      steps {
+        withMaven {
+          // Build the project
+          sh "mvn clean install -DskipUnitTests=true -DskipTests=true -Dinvoker.skip=true -DskipITs=true -B"
+        }
+      }
+      post {
+        success {
+          // Display success message when Build stage is completed successfully
+          echo "Build stage successfully completed!"
+        }
+        failure {
+          // Display failure message if Build stage fails
+          echo "Build stage failed!"
+        }
+      }
     }
 
-    stages {
-        stage("Build") {
-            steps {
-                withMaven {
-                    // Build the project
-                    sh "mvn clean install -DskipUnitTests=true -DskipTests=true -Dinvoker.skip=true -DskipITs=true -B"
-                }
-            }
-            post {
-                success {
-                    // Display success message when Build stage is completed successfully
-                    echo "Build stage successfully completed!"
-                }
-                failure {
-                    // Display failure message if Build stage fails
-                    echo "Build stage failed!"
-                }
-            }
+    stage('Generate SBOM') {
+      steps {
+        withMaven {
+          // Generate the SBOM file using CycloneDX
+          sh 'mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom'
         }
-
-        stage('Generate SBOM') {
-            steps {
-                withMaven {
-                    // Generate the SBOM file using CycloneDX
-                    sh 'mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom'
-                }
-            }
-            post {
-                success {
-                    // Display success message when SBOM is generated successfully
-                    echo "SBOM file successfully generated!"
-                }
-                failure {
-                    // Display failure message if SBOM generation fails
-                    echo "SBOM file generation failed!"
-                }
-                always {
-                    // Archive the generated SBOM file for reference
-                    archiveArtifacts allowEmptyArchive: true, artifacts: '**/target/bom*.{json,xml}'
-                }
-            }
+      }
+      post {
+        success {
+          // Display success message when SBOM is generated successfully
+          echo "SBOM file successfully generated!"
         }
-
-        stage('Dependency Vulnerability Check') {
-            steps {
-                withMaven {
-                    // Run the OWASP Dependency-Check for vulnerabilities
-                    sh 'mvn org.owasp:dependency-check-maven:check -DfailBuildOnCVSS=10.0 -Dformats=HTML,XML,JSON'
-                }
-            }
-            post {
-                success {
-                    // Display success message when Dependency Vulnerability Check is successful
-                    echo "Dependency Vulnerability check completed successfully!"
-                }
-                failure {
-                    // Display failure message if the Dependency Vulnerability Check fails
-                    echo "Dependency Vulnerability Check failed!"
-                }
-                always {
-                    // Archive the reports generated by Dependency-Check
-                    archiveArtifacts allowEmptyArchive: true, artifacts: '**/target/dependency-check-report*.{html,xml,json}'
-                }
-            }
+        failure {
+          // Display failure message if SBOM generation fails
+          echo "SBOM file generation failed!"
         }
-
-        stage('Upload SBOM to Dependency-Track') {
-            steps {
-                script {
-                    // Check if SBOM file exists
-                    if (fileExists(SBOM_FILE_PATH)) {
-                        echo "Uploading SBOM to Dependency-Track..."
-
-                        // Upload the SBOM file to Dependency-Track via its API
-                        sh """
-                            curl -X POST ${DEP_TRACK_API_URL}/v1/bom \
-                                 -H "Authorization: ApiKey ${DEP_TRACK_API_KEY}" \
-                                 -F "bom=@${SBOM_FILE_PATH}" \
-                                 -F "project=b7968dbc-9345-4373-887f-425218725981"
-                        """
-                    } else {
-                        echo "SBOM file not found at ${SBOM_FILE_PATH}!"
-                    }
-                }
-            }
-            post {
-                success {
-                    // Display success message when SBOM is uploaded to Dependency-Track
-                    echo "SBOM file successfully uploaded to Dependency-Track!"
-                }
-                failure {
-                    // Display failure message if SBOM upload fails
-                    echo "Failed to upload SBOM file to Dependency-Track!"
-                }
-            }
+        always {
+          archiveArtifacts allowEmptyArchive: true, artifacts: '**/target/bom.json'
+          archiveArtifacts allowEmptyArchive: true, artifacts: '**/target/bom.xml'
         }
+      }
     }
+
+    stage('Upload SBOM to Dependency-Track') {
+      steps {
+        script {
+          if (fileExists(SBOM_FILE_PATH)) {
+            echo 'Uploading SBOM to Dependency-Track...'
+            sh ""
+            "
+            curl - X "POST"
+            "${DEP_TRACK_API_URL}/v1/bom"\ -
+            H 'Content-Type: multipart/form-data'\ -
+              H 'X-API-Key:  ${DEP_TRACK_API_KEY}'\ -
+              F "autoCreate=false"\ -
+              F "project=26fe3e22-c99d-454e-974d-80aee66c3149"\ -
+              F "bom=@${SBOM_FILE_PATH}"
+            ""
+            "
+          } else {
+            echo "SBOM file not found at ${SBOM_FILE_PATH}!"
+          }
+        }
+      }
+      post {
+        success {
+          echo 'SBOM file successfully uploaded to Dependency-Track!'
+        }
+        failure {
+          echo 'Failed to upload SBOM file to Dependency-Track!'
+        }
+      }
+    }
+
+    stage('Check Dependency Vulnerabilities') {
+      steps {
+        script {
+          echo 'Checking vulnerabilities in Dependency-Track...'
+
+
+          // Install jq if not present
+          sh "command -v jq >/dev/null 2>&1 || (echo 'Installing jq...' && sudo apt update && sudo apt install -y jq)"
+          def projectUuid = '26fe3e22-c99d-454e-974d-80aee66c3149'
+          def response = sh(
+            script: ""
+            "
+            curl - s - X "GET"
+            "${DEP_TRACK_API_URL}/v1/finding/project/${projectUuid}"\\ -
+            H 'X-API-Key: ${DEP_TRACK_API_KEY}' | \\
+            jq '[.[] | select(.analysis.isSuppressed == false) | .vulnerability.severity] |
+            group_by(.) |
+            map({
+              (.[0]): length
+            }) |
+            add '
+            ""
+            ",
+            returnStdout: true
+          ).trim()
+          echo "Vulnerability Report: ${response}"
+
+          def vulnData = readJSON text: response
+          def criticalCount = vulnData.CRITICAL ? : 0
+          def highCount = vulnData.HIGH ? : 0
+          def mediumCount = vulnData.MEDIUM ? : 0
+          def lowCount = vulnData.LOW ? : 0
+          def unassignedCount = vulnData.UNASSIGNED ? : 0
+          echo "Critical: ${criticalCount}, High: ${highCount}, Medium: ${mediumCount}, Low: ${lowCount}, Unassigned: ${unassignedCount}"
+          def vulnerabilitiesExist = (criticalCount > 0 || highCount > 0)
+          if (vulnerabilitiesExist) {
+            error "Pipeline aborted due to detected vulnerabilities: CRITICAL=${criticalCount}, HIGH=${highCount}"
+          } else {
+            echo 'No critical vulnerabilities found.'
+          }
+        }
+      }
+    }
+
+  }
 }
-
